extensions:
  health_check:
  pprof:
    endpoint: localhost:1777
  zpages:
    endpoint: localhost:55679
  oidc/server:
    issuer_url: https://idcs-146b14cb77e84595a3c5d99b03d5debe.identity.oraclecloud.com:443/
    audience: collector
    attribute: authorization

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
        tls:
          ca_file: /etc/otelcol-audit/ca.pem
          cert_file: /etc/otelcol-audit/cert.pem
          key_file: /etc/otelcol-audit/key.pem
        auth:
          authenticator: oidc/server
      http:
        endpoint: "0.0.0.0:4318"
        tls:
          ca_file: /etc/otelcol-audit/ca.pem
          cert_file: /etc/otelcol-audit/cert.pem
          key_file: /etc/otelcol-audit/key.pem
        auth:
          authenticator: oidc/server

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: "otel-collector"
          scrape_interval: 60s
          static_configs:
            - targets: ["localhost:8888"]

  hostmetrics:
    scrapers:
      cpu:
      memory:
      disk:
      network:
      filesystem:
      processes:
      process:
        mute_process_name_error: true
        mute_process_exe_error: true
        mute_process_io_error: true
        mute_process_user_error: true
        mute_process_cgroup_error: true

processors:
  batch:

exporters:
  file:
    path: "/var/log/otelcol/collector.json"
    rotation:
  file/local:
    path: "/var/log/otelcol/collector-local.json"
    rotation:
  debug:

service:
  pipelines:
    traces/remote:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file]

    metrics/remote:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file]

    metrics/local:
      receivers: [prometheus, hostmetrics]
      processors: [batch]
      exporters: [debug, file/local]

    logs/remote:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, file]

  extensions: [oidc/server, health_check, pprof, zpages]
