extensions:
  health_check:
  pprof:
    endpoint: localhost:1777
  zpages:
    endpoint: localhost:55679
  oauth2client/client:
    client_id: 61ab6521f4bd4d2aa29f2c67915ac7d6
    client_secret: ${env:OTEL_COLLECTOR_OAUTH2_CLIENT_SECRET}
    token_url: https://idcs-146b14cb77e84595a3c5d99b03d5debe.identity.oraclecloud.com:443/oauth2/v1/token

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 60s
        static_configs:
        - targets: ['localhost:8888']
  
  hostmetrics:
    scrapers:
      cpu:
      memory:
      disk:
      network:
      filesystem:
      processes:
      process:

processors:
  batch:

exporters:
  otlp/secure:
    endpoint: gateway:4317
    tls:
      ca_file: /etc/otelcol/ca.pem
      cert_file: /etc/otelcol/cert.pem
      key_file: /etc/otelcol/key.pem
    auth:
      authenticator: oauth2client/client


service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/secure]

    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [otlp/secure]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/secure]

  extensions: [oauth2client/client, health_check, pprof, zpages]